use_frameworks!

platform :ios, '8.0'

target 'BMSocketManager_Example' do
  pod 'SocketRocket'
  pod 'BMSocketManager', :path => '../'

  target 'BMSocketManager_Tests' do
    inherit! :search_paths

    
  end
end
